baseURL = "https://lngv.me/"
languageCode = "en-uk"
title = "Overthinking blogging"
theme = "tale"
publishDir = "luanadotcom.github.io"
sectionPagesMenu = "main"
enableEmoji = true

[Author]
name = "Luana"
