baseURL = "/"
languageCode = "en-uk"
title = "Overthinking blogging"
theme = "tale"
publishDir = "public"
enableEmoji = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 0

[Author]
name = "Luana"
